version: '3.8'
services:
  micron:
    build: .
    volumes:
      - .:/go/src/app
    ports:
      - "8080:8080"
    environment:
      - DATABASE_CONNECTION_STRING=mongodb://database:27017
      - DATABASE_CONNECTION_USERNAME=root
      - DATABASE_CONNECTION_PASSWORD=root
      - JWT_SECRET=MlkMIlRWTcmkqCKKz9gyriGQM7
      - SCRAPING_ENABLED=false
    depends_on:
      - database
  database:
    image: mongo:latest
    container_name: 'micron_db'
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: admin
    ports:
      - '27017-27019:27017-27019'
    volumes:
      - './mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro'
